version: '3'

vars:
  CONFIG_FILE: ./deno.json
  IMPORT_MAP: ./import_map.json
  LOCK_FILE: ./.lock.json
  COVERAGE_DIR: ./tests/cov_profile

env:
  DENO_DIR: ./.deno_dir

tasks:
  fmt:
    cmds:
      - deno fmt 
          --config {{.CONFIG_FILE}}

  lint:
    cmds:
      - deno lint 
          --config {{.CONFIG_FILE}}

  test:
    deps: 
      - unit-test
      - integration-test

  unit-test:
    cmds:
      - deno --unstable test
          --config {{.CONFIG_FILE}}
          --import-map={{.IMPORT_MAP}}
          --allow-all
          --no-check
          --coverage={{.COVERAGE_DIR}}/unit
          --jobs
          --shuffle
          {{.CLI_ARGS}}
          tests/unit/*

  integration-test:
    cmds:
      - deno --unstable test
          --config {{.CONFIG_FILE}}
          --import-map={{.IMPORT_MAP}}
          --allow-all
          --no-check
          --coverage={{.COVERAGE_DIR}}/integration
          --jobs
          --shuffle
          {{.CLI_ARGS}}
          tests/integration/*

  coverage:
    cmds:
      - deno --unstable coverage
          {{.COVERAGE_DIR}}
          --lcov 
          --include=packages
          --output={{.COVERAGE_DIR}}/unit/cov_profile.lcov
      - deno --unstable coverage
          {{.COVERAGE_DIR}}
          --lcov 
          --include=packages
          --output={{.COVERAGE_DIR}}/integration/cov_profile.lcov

  dev-doc:
    env:
      FRUGAL_DEV: true
    cmds:
      - deno --unstable run
          --config {{.CONFIG_FILE}}
          --import-map={{.IMPORT_MAP}}
          --allow-all
          --no-check
          --watch=docs/data
          {{.CLI_ARGS}}
          docs/serve.ts

  build-doc:
    cmds:
      - deno --unstable run
          --config {{.CONFIG_FILE}}
          --import-map={{.IMPORT_MAP}}
          --allow-all
          --no-check
          {{.CLI_ARGS}}
          docs/build.ts

  serve-doc:
    cmds:
      - deno --unstable run
          --config {{.CONFIG_FILE}}
          --import-map={{.IMPORT_MAP}}
          --allow-all
          --no-check
          {{.CLI_ARGS}}
          docs/serve.ts

  example:
    cmds:
      - deno --unstable run
          --config {{.CONFIG_FILE}}
          --import-map={{.IMPORT_MAP}}
          --allow-all
          --no-check
          {{.CLI_ARGS}}