version: '3'

vars:
  CONFIG_FILE: ./deno.json
  IMPORT_MAP: ./import_map.json
  LOCK_FILE: ./.lock.json
  COVERAGE_DIR: ./tests/cov_profile
  #authorizations
  ALLOW_READ: .
  ALLOW_WRITE: .
  ALLOW_NET_REPO: deno.land,esm.sh,cdn.esm.sh,cdn.jsdelivr.net,unpkg.com
  ALLOW_NET_SERVER: 0.0.0.0:8000
  ALLOW_ENV: NODE_ENV,DENO_DIR

env:
  DENO_DIR: ./.deno_dir

tasks:
  fmt:
    cmds:
      - deno fmt 
          --config {{.CONFIG_FILE}}

  test:
    deps: 
      - unit-test
      - integration-test

  unit-test:
    cmds:
      - deno --unstable test
          --config {{.CONFIG_FILE}}
          --import-map={{.IMPORT_MAP}}
          --allow-read={{.ALLOW_READ}}
          --coverage={{.COVERAGE_DIR}}/unit
          --jobs
          --shuffle
          {{.CLI_ARGS}}
          tests/unit/*

  integration-test:
    cmds:
      - deno --unstable test
          --config {{.CONFIG_FILE}}
          --import-map={{.IMPORT_MAP}}
          --allow-read={{.ALLOW_READ}}
          --allow-write={{.ALLOW_WRITE}}
          --coverage={{.COVERAGE_DIR}}/integration
          --jobs
          --shuffle
          {{.CLI_ARGS}}
          tests/integration/*

  coverage:
    cmds:
      - deno --unstable coverage
          {{.COVERAGE_DIR}}
          --lcov 
          --include=packages
          --output={{.COVERAGE_DIR}}/unit/cov_profile.lcov
      - deno --unstable coverage
          {{.COVERAGE_DIR}}
          --lcov 
          --include=packages
          --output={{.COVERAGE_DIR}}/integration/cov_profile.lcov

  example:
    cmds:
      - deno --unstable run
          --config {{.CONFIG_FILE}}
          --import-map={{.IMPORT_MAP}}
          --allow-read={{.ALLOW_READ}}
          --allow-write={{.ALLOW_WRITE}}
          --allow-net={{.ALLOW_NET_REPO}},{{.ALLOW_NET_SERVER}}
          --allow-env={{.ALLOW_ENV}}
          --no-check
          {{.CLI_ARGS}}