name: test

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: run tests

    strategy:
      matrix:
        deno-version: [1.x, canary]
        os: [macOS-latest, windows-latest, ubuntu-latest]
        include:
          - deno-version: 1.20.x
            os: ubuntu-latest
            coverage: true

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout project
      uses: actions/checkout@v2

    - name: install task
      uses: arduino/setup-task@v1

    - name: install deno ${{ matrix.deno-version }}
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: run lint
      run: task lint

    - name: run test
      run: task test

    - name: generate coverage report
      if: matrix.coverage
      run: task coverage
      
    - name: unit test code coverage
      if: matrix.coverage
      uses: codecov/codecov-action@v2
      with: 
        files: ./tests/cov_profile/unit/cov_profile.lcov
        flags: unit

    - name: integration test code coverage
      if: matrix.coverage
      uses: codecov/codecov-action@v2
      with: 
        files: ./tests/cov_profile/unit/cov_profile.lcov
        flags: integration
